apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "pymyredis.fullname" . }}-config
  labels:
    {{- include "pymyredis.labels" . | nindent 4 }}
data:
  config.py: |
    {{- .Values.config | nindent 4 }}
