apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "pymyredis.fullname" . }}-pvc
  labels:
    {{- include "pymyredis.labels" . | nindent 4 }}
spec:
  accessModes:
    - {{ .Values.persistence.accessMode }}
  resources:
    requests:
      storage: {{ .Values.persistence.size }}
  {{- if .Values.persistence.storageClass }}
  storageClassName: {{ .Values.persistence.storageClass }}
  {{- end }}
